// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYZptH8zo-koMjkpmLVGuc4jb3CzLRKHQ',
    appId: '1:563478870118:web:af01ad54cf89157472d5a7',
    messagingSenderId: '563478870118',
    projectId: 'netflex-ui-test',
    authDomain: 'netflex-ui-test.firebaseapp.com',
    storageBucket: 'netflex-ui-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7lakonMEtZy8JaGTFt7hu_NyKqPmw2C4',
    appId: '1:563478870118:android:a4dc532c0a9fdac472d5a7',
    messagingSenderId: '563478870118',
    projectId: 'netflex-ui-test',
    storageBucket: 'netflex-ui-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZIONZKoW9letSPmvDT9m8pfcOSFyIXs',
    appId: '1:563478870118:ios:7ec2081f89a9f95b72d5a7',
    messagingSenderId: '563478870118',
    projectId: 'netflex-ui-test',
    storageBucket: 'netflex-ui-test.appspot.com',
    iosBundleId: 'com.example.netflexui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQZIONZKoW9letSPmvDT9m8pfcOSFyIXs',
    appId: '1:563478870118:ios:827de15bc9fef9de72d5a7',
    messagingSenderId: '563478870118',
    projectId: 'netflex-ui-test',
    storageBucket: 'netflex-ui-test.appspot.com',
    iosBundleId: 'com.example.netflexui.RunnerTests',
  );
}
